"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { cn, formatDateTime } from "@/lib/utils";
import { GlassCard, Badge, Skeleton } from "@/components/ui/core";
import { Button, Input, Select } from "@/components/ui/forms";
import { CAMERA_LOCATIONS, generatePlateNumber } from "@/lib/mock-data";
import {
  FolderLock, Image as ImageIcon, ShieldCheck, Download, Search,
  Filter, Calendar, ExternalLink, HardDrive, Cpu, MoreHorizontal,
  Info, Trash2, CheckCircle2, AlertTriangle, Fingerprint
} from "lucide-react";

// ============================================================
// EVIDENCE LOCKER PAGE
// ============================================================

interface EvidenceItem {
  id: string;
  plate: string;
  camera: string;
  district: string;
  timestamp: Date;
  cryptohash: string;
  officer: string;
  type: string;
  hasAttachment: boolean;
}

const EVIDENCE_LIST: EvidenceItem[] = [
  {
    id: "EVD-209",
    plate: "AP39AB1234",
    camera: "CAM-001 (NH-16 Bypass)",
    district: "Ongole",
    timestamp: new Date(Date.now() - 15 * 60000),
    cryptohash: "sha256-4c8d5d9a9f0e1a2b3c4d5e6f7a8b9c0d",
    officer: "SI Ravi Kumar",
    type: "Clone Verification",
    hasAttachment: true,
  },
  {
    id: "EVD-184",
    plate: "AP16CD5678",
    camera: "CAM-003 (Santhi Nagar)",
    district: "Ongole",
    timestamp: new Date(Date.now() - 45 * 60000),
    cryptohash: "sha256-8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d",
    officer: "ASI Lakshmi",
    type: "Stolen Target Case",
    hasAttachment: true,
  },
  {
    id: "EVD-172",
    plate: "AP37EF9012",
    camera: "CAM-005 (Chirala Checkpost)",
    district: "Chirala",
    timestamp: new Date(Date.now() - 120 * 60000),
    cryptohash: "sha256-5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    officer: "SI Ramesh",
    type: "Blacklist Watch",
    hasAttachment: false,
  }
];

export default function EvidenceLockerPage() {
  const [evidence, setEvidence] = useState<EvidenceItem[]>(EVIDENCE_LIST);
  const [selectedItem, setSelectedItem] = useState<EvidenceItem | null>(EVIDENCE_LIST[0]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setTimeout(() => {
      if (query.trim()) {
        const filtered = EVIDENCE_LIST.filter(
          (item) =>
            item.plate.toLowerCase().includes(query.toLowerCase()) ||
            item.id.toLowerCase().includes(query.toLowerCase())
        );
        setEvidence(filtered);
      } else {
        setEvidence(EVIDENCE_LIST);
      }
      setLoading(false);
    }, 400);
  };

  return (
    <div className="space-y-6 max-w-[1600px] mx-auto">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <FolderLock size={14} className="text-electric-400" />
            <span className="text-[11px] text-electric-400 font-mono font-medium tracking-widest uppercase">Digital Evidence Vault</span>
          </div>
          <h1 className="font-heading font-bold text-2xl text-white">Evidence Locker</h1>
          <p className="text-navy-300 text-xs">Chain of custody logs and secure encrypted visual crops generated by camera hits.</p>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" icon={<Download size={13} />}>Download Vault Backup</Button>
          <Button variant="secondary" size="sm" icon={<ShieldCheck size={13} />} className="text-cyan-400 border-cyan-500/20">
            Audit Custody Logs
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left columns - evidence items list */}
        <div className="lg:col-span-2 space-y-4">
          <GlassCard className="p-4">
            <form onSubmit={handleSearch} className="flex gap-2 mb-4">
              <Input
                placeholder="Search by Plate number, Case ID..."
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                className="flex-1"
                icon={<Search size={14} />}
              />
              <Button type="submit" variant="secondary" loading={loading}>
                Filter
              </Button>
            </form>

            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse text-xs text-navy-200">
                <thead>
                  <tr className="border-b border-navy-700/30 text-[10px] uppercase tracking-widest text-navy-400 font-bold">
                    <th className="py-2.5 px-3">Evidence ID</th>
                    <th className="py-2.5 px-3">License Plate</th>
                    <th className="py-2.5 px-3">Incident Type</th>
                    <th className="py-2.5 px-3">Time Filed</th>
                    <th className="py-2.5 px-3 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {evidence.map((item) => (
                    <tr
                      key={item.id}
                      onClick={() => setSelectedItem(item)}
                      className={cn(
                        "border-b border-navy-700/20 hover:bg-navy-800/20 transition-colors cursor-pointer",
                        selectedItem?.id === item.id && "bg-electric-500/5"
                      )}
                    >
                      <td className="py-3 px-3 font-mono text-white font-semibold">{item.id}</td>
                      <td className="py-3 px-3 font-mono font-bold text-navy-200">{item.plate}</td>
                      <td className="py-3 px-3 text-navy-300">{item.type}</td>
                      <td className="py-3 px-3 text-navy-400 font-mono">{formatDateTime(item.timestamp)}</td>
                      <td className="py-3 px-3 text-right">
                        <Button variant="ghost" size="xs" icon={<ExternalLink size={11} />} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </GlassCard>
        </div>

        {/* Right column - active evidence item deep dive details */}
        <div>
          {selectedItem ? (
            <GlassCard className="p-5 space-y-4">
              <div className="flex justify-between items-center pb-2 border-b border-navy-700/30">
                <div>
                  <span className="text-[10px] text-navy-500 font-mono font-semibold uppercase">Surveillance Audit File</span>
                  <h3 className="text-sm font-semibold text-navy-100 font-heading">{selectedItem.id}</h3>
                </div>
                <Badge variant="success">HASH SECURED</Badge>
              </div>

              {/* Simulated camera capture photo crop */}
              <div className="aspect-video bg-navy-900 border border-navy-700/40 rounded-xl relative overflow-hidden flex items-center justify-center">
                <ImageIcon size={32} className="text-navy-500/50" />
                <div className="absolute top-2 left-2 text-[9px] font-mono bg-navy-950/80 text-navy-300 px-2 py-0.5 rounded">
                  SURVEILLANCE CROP
                </div>
                <div className="absolute bottom-2 left-2 text-[10px] text-white bg-navy-950/80 px-2 py-1 rounded font-mono">
                  {selectedItem.plate}
                </div>
              </div>

              <div className="space-y-3 text-xs">
                <div>
                  <span className="text-[10px] text-navy-500 block uppercase tracking-wider">Observe location</span>
                  <span className="text-navy-200 font-semibold block">{selectedItem.camera}</span>
                </div>
                <div>
                  <span className="text-[10px] text-navy-500 block uppercase tracking-wider">Custodian Officer</span>
                  <span className="text-navy-200 font-semibold block">{selectedItem.officer}</span>
                </div>
                <div>
                  <span className="text-[10px] text-navy-500 block uppercase tracking-wider">Digital Hash Signature</span>
                  <span className="text-navy-300 font-mono break-all bg-navy-900/60 p-2 rounded block mt-1 border border-navy-700/30">
                    {selectedItem.cryptohash}
                  </span>
                </div>
              </div>

              <div className="h-px bg-navy-700/30 w-full my-4" />

              <div className="flex justify-end gap-2">
                <Button variant="ghost" size="sm" icon={<Trash2 size={13} className="text-crimson-400" />}>
                  Purge Item
                </Button>
                <Button variant="secondary" size="sm" icon={<Download size={13} />}>
                  Export Evidence
                </Button>
              </div>
            </GlassCard>
          ) : (
            <GlassCard className="p-12 text-center text-navy-500 font-mono text-xs">
              Select an evidence file record from the repository to check audit credentials.
            </GlassCard>
          )}
        </div>
      </div>
    </div>
  );
}
